### ISSUE TITLE
camera PTZ default speeds

### ISSUE THREAD

**Issue by nottooloud** [bitfocus/companion-module-cisco-webex#3]
Testing on TC 7.3.

Camera pan, tilt, and zoom speeds currently default to 0. That's not a valid speed, and the commands don't work. They all three need to be set to at least 1 in each command, including the stop commands.

Response is very good.

BTW, not seeing any difference between selecting websocket or SSH.

**Comment by SveinTerje** [comment]
This is an old issue and no longer relevant, should be closed
