### ISSUE TITLE
Set camera position parameters?

### ISSUE THREAD

**Issue by nottooloud** [bitfocus/companion-module-cisco-webex#4]
TC 7.3

I can't get set camera position to do anything. It has a parameter called Roll. That word doesn't appear in the TC 7.3 API. Is it in other firmwares, or is this a left over bit of code ported from a different camera?

A note on PTZ defaults, while the pan and tilt commands will take values of +-65535, and zoom and focus will take values of 0-65535, most of those ranges are nonsense values. The camera I'm testing right now pans from 0-816, tilts from 7-212, zooms from 0-2885, and the useful focus range is about 4500-4600. You can literally make it focus on dust on its own front element at wider zooms.

**Comment by SveinTerje** [comment]
This is an old issue and no longer relevant, should be closed
